const translations={
  en:{navServices:'Services',navGallery:'Gallery',navFaq:'FAQs',navContact:'Contact',dropPainting:'Painting & decorating',dropJobs:'Rooms, homes and property work',dropBeforeAfter:'Before & after',dropProjects:'Project photos',dropTravel:'Travel area',dropQuote:'Getting a quote',dropPaint:'Paint & materials',kicker:'PAINTING & DECORATING',intro:'Simple, tidy painting and decorating. Tell Ahmed what you need and he’ll tell you if the job is a good fit.',callAhmed:'Call / WhatsApp Ahmed',seeGallery:'See gallery',servicesTitle:'Painting & decorating',servicesCopy:'Need a room, home, rental property or another space painted? Give Ahmed a call, describe the job and he’ll tell you what he can do.',s1:'Interior',s1d:'Walls, ceilings and general decorating enquiries.',s2:'Exterior',s2d:'Ask Ahmed about the outside work you have in mind.',s3:'Property refresh',s3d:'Rooms, homes, rentals and smaller jobs can all be discussed.',galleryTitle:'Gallery',galleryCopy:'Before-and-after project photos can go here. The split layout is ready for Ahmed’s own photographs.',faqTitle:'Frequently asked questions',fq1:'How far are you prepared to travel?',fa1:'Tell Ahmed where the job is and he’ll let you know if it is within his normal working area.',fq2:'How do I get a quote?',fa2:'Call or WhatsApp Ahmed with a short description of the job. Photos and the location are useful too.',fq3:'Can I send photos first?',fa3:'Yes. Photos are a simple way to show the room, surface or area you want painted before discussing the job.',fq4:'Who supplies the paint?',fa4:'Ask Ahmed when you speak. Paint and materials can be discussed for each individual job.',fq5:'How long will the work take?',fa5:'That depends on the size of the job and the preparation needed. Ahmed can give you a better idea once he knows what is involved.',fq6:'What should I send when I contact you?',fa6:'The location, a few photos and a short description are the easiest starting point.',contactTitle:'Give Ahmed a call',contactCopy:'The quickest way to start is to call or WhatsApp Ahmed and tell him what you need.',phoneLabel:'Phone / WhatsApp',phonePlaceholder:'Ahmed’s number to be added',hide:'Hide',show:'Show'},
  ar:{navServices:'الخدمات',navGallery:'المعرض',navFaq:'الأسئلة',navContact:'التواصل',dropPainting:'دهان وديكور',dropJobs:'غرف ومنازل وعقارات',dropBeforeAfter:'قبل وبعد',dropProjects:'صور الأعمال',dropTravel:'منطقة العمل',dropQuote:'طلب سعر',dropPaint:'الدهان والمواد',kicker:'دهان وديكور',intro:'دهان وديكور بشكل بسيط ومرتب. أخبر أحمد بما تحتاجه وسيخبرك إن كان العمل مناسباً له.',callAhmed:'اتصل / واتساب أحمد',seeGallery:'شاهد المعرض',servicesTitle:'دهان وديكور',servicesCopy:'هل تحتاج إلى دهان غرفة أو منزل أو عقار؟ اتصل بأحمد واشرح له العمل وسيخبرك بما يمكنه القيام به.',s1:'داخلي',s1d:'الجدران والأسقف وأعمال الديكور العامة.',s2:'خارجي',s2d:'اسأل أحمد عن العمل الخارجي الذي تحتاجه.',s3:'تجديد العقار',s3d:'يمكن مناقشة الغرف والمنازل والعقارات والأعمال الصغيرة.',galleryTitle:'المعرض',galleryCopy:'يمكن إضافة صور أعمال قبل وبعد هنا لاحقاً باستخدام صور أحمد الحقيقية.',faqTitle:'الأسئلة الشائعة',fq1:'إلى أي مسافة أنت مستعد للسفر؟',fa1:'أخبر أحمد بموقع العمل وسيخبرك إذا كان ضمن منطقة عمله المعتادة.',fq2:'كيف أحصل على سعر؟',fa2:'اتصل بأحمد أو أرسل له عبر واتساب وصفاً قصيراً للعمل. الصور والموقع مفيدان أيضاً.',fq3:'هل يمكنني إرسال صور أولاً؟',fa3:'نعم. الصور طريقة بسيطة لعرض المكان أو السطح قبل مناقشة العمل.',fq4:'من يوفر الدهان؟',fa4:'اسأل أحمد عند التواصل. يمكن الاتفاق على الدهان والمواد لكل عمل.',fq5:'كم يستغرق العمل؟',fa5:'يعتمد ذلك على حجم العمل والتحضير المطلوب. يمكن لأحمد إعطاؤك فكرة أفضل بعد معرفة التفاصيل.',fq6:'ماذا أرسل عند التواصل؟',fa6:'الموقع وبعض الصور ووصف قصير هي أفضل بداية.',contactTitle:'اتصل بأحمد',contactCopy:'أسرع طريقة هي الاتصال بأحمد أو مراسلته على واتساب وشرح ما تحتاجه.',phoneLabel:'الهاتف / واتساب',phonePlaceholder:'سيتم إضافة رقم أحمد',hide:'إخفاء',show:'إظهار'},
  pl:{navServices:'Usługi',navGallery:'Galeria',navFaq:'FAQ',navContact:'Kontakt',dropPainting:'Malowanie i dekorowanie',dropJobs:'Pokoje, domy i nieruchomości',dropBeforeAfter:'Przed i po',dropProjects:'Zdjęcia prac',dropTravel:'Obszar dojazdu',dropQuote:'Wycena',dropPaint:'Farba i materiały',kicker:'MALOWANIE I DEKOROWANIE',intro:'Proste i schludne malowanie. Powiedz Ahmedowi, czego potrzebujesz, a on powie, czy może wykonać pracę.',callAhmed:'Zadzwoń / WhatsApp Ahmed',seeGallery:'Zobacz galerię',servicesTitle:'Malowanie i dekorowanie',servicesCopy:'Potrzebujesz pomalować pokój, dom, mieszkanie na wynajem lub inną przestrzeń? Zadzwoń do Ahmeda i opisz pracę.',s1:'Wnętrza',s1d:'Ściany, sufity i ogólne prace dekoracyjne.',s2:'Na zewnątrz',s2d:'Zapytaj Ahmeda o planowane prace zewnętrzne.',s3:'Odświeżenie nieruchomości',s3d:'Można omówić pokoje, domy, wynajmy i mniejsze prace.',galleryTitle:'Galeria',galleryCopy:'Tutaj mogą pojawić się zdjęcia przed i po. Układ jest gotowy na prawdziwe zdjęcia Ahmeda.',faqTitle:'Najczęstsze pytania',fq1:'Jak daleko jesteś gotowy dojechać?',fa1:'Podaj Ahmedowi lokalizację, a powie, czy znajduje się w jego zwykłym obszarze pracy.',fq2:'Jak otrzymać wycenę?',fa2:'Zadzwoń lub napisz do Ahmeda na WhatsApp z krótkim opisem pracy. Zdjęcia i lokalizacja też pomagają.',fq3:'Czy mogę najpierw wysłać zdjęcia?',fa3:'Tak. Zdjęcia to prosty sposób, aby pokazać pomieszczenie lub powierzchnię przed rozmową.',fq4:'Kto kupuje farbę?',fa4:'Zapytaj Ahmeda podczas rozmowy. Farbę i materiały można ustalić indywidualnie dla każdego zlecenia.',fq5:'Jak długo potrwa praca?',fa5:'To zależy od wielkości pracy i potrzebnego przygotowania. Ahmed poda lepsze przybliżenie po poznaniu szczegółów.',fq6:'Co wysłać przy pierwszym kontakcie?',fa6:'Lokalizacja, kilka zdjęć i krótki opis to najlepszy początek.',contactTitle:'Zadzwoń do Ahmeda',contactCopy:'Najszybciej po prostu zadzwoń lub napisz do Ahmeda na WhatsApp i powiedz, czego potrzebujesz.',phoneLabel:'Telefon / WhatsApp',phonePlaceholder:'Numer Ahmeda do dodania',hide:'Ukryj',show:'Pokaż'},
  lt:{navServices:'Paslaugos',navGallery:'Galerija',navFaq:'DUK',navContact:'Kontaktai',dropPainting:'Dažymas ir apdaila',dropJobs:'Kambariai, namai ir būstas',dropBeforeAfter:'Prieš ir po',dropProjects:'Darbų nuotraukos',dropTravel:'Aptarnaujama vietovė',dropQuote:'Kainos aptarimas',dropPaint:'Dažai ir medžiagos',kicker:'DAŽYMAS IR APDAILA',intro:'Paprastas ir tvarkingas dažymas. Pasakykite Ahmedui, ko reikia, ir jis pasakys, ar gali atlikti darbą.',callAhmed:'Skambinti / WhatsApp Ahmedui',seeGallery:'Žiūrėti galeriją',servicesTitle:'Dažymas ir apdaila',servicesCopy:'Reikia nudažyti kambarį, namą, nuomojamą būstą ar kitą erdvę? Paskambinkite Ahmedui ir trumpai paaiškinkite darbą.',s1:'Vidaus darbai',s1d:'Sienos, lubos ir bendri apdailos darbai.',s2:'Lauko darbai',s2d:'Paklauskite Ahmedo apie planuojamą lauko darbą.',s3:'Būsto atnaujinimas',s3d:'Galima aptarti kambarius, namus, nuomojamą būstą ir mažesnius darbus.',galleryTitle:'Galerija',galleryCopy:'Čia gali būti tikros Ahmedo darbų nuotraukos prieš ir po. Išdėstymas jau paruoštas.',faqTitle:'Dažniausi klausimai',fq1:'Kaip toli esate pasirengęs vykti?',fa1:'Pasakykite Ahmedui darbo vietą ir jis pasakys, ar ji patenka į įprastą darbo zoną.',fq2:'Kaip gauti kainą?',fa2:'Paskambinkite arba parašykite Ahmedui per WhatsApp ir trumpai apibūdinkite darbą. Nuotraukos ir vieta taip pat padeda.',fq3:'Ar galiu pirmiausia atsiųsti nuotraukas?',fa3:'Taip. Nuotraukos yra paprastas būdas parodyti patalpą ar paviršių prieš aptariant darbą.',fq4:'Kas perka dažus?',fa4:'Paklauskite Ahmedo kalbėdami. Dažus ir medžiagas galima sutarti kiekvienam darbui atskirai.',fq5:'Kiek truks darbas?',fa5:'Tai priklauso nuo darbo dydžio ir reikalingo paruošimo. Ahmedas galės pasakyti tiksliau žinodamas detales.',fq6:'Ką atsiųsti susisiekiant?',fa6:'Vieta, kelios nuotraukos ir trumpas aprašymas yra paprasčiausia pradžia.',contactTitle:'Paskambinkite Ahmedui',contactCopy:'Greičiausias būdas pradėti — paskambinti arba parašyti Ahmedui per WhatsApp ir pasakyti, ko reikia.',phoneLabel:'Telefonas / WhatsApp',phonePlaceholder:'Ahmedo numeris bus pridėtas',hide:'Slėpti',show:'Rodyti'},
  ro:{navServices:'Servicii',navGallery:'Galerie',navFaq:'Întrebări',navContact:'Contact',dropPainting:'Zugrăveli și finisaje',dropJobs:'Camere, case și proprietăți',dropBeforeAfter:'Înainte și după',dropProjects:'Fotografii lucrări',dropTravel:'Zona de deplasare',dropQuote:'Ofertă',dropPaint:'Vopsea și materiale',kicker:'ZUGRĂVELI ȘI FINISAJE',intro:'Lucrări simple și ordonate. Spune-i lui Ahmed ce ai nevoie și îți va spune dacă lucrarea i se potrivește.',callAhmed:'Sună / WhatsApp Ahmed',seeGallery:'Vezi galeria',servicesTitle:'Zugrăveli și finisaje',servicesCopy:'Ai nevoie să vopsești o cameră, o casă, o locuință închiriată sau alt spațiu? Sună-l pe Ahmed și descrie lucrarea.',s1:'Interior',s1d:'Pereți, tavane și lucrări generale de finisare.',s2:'Exterior',s2d:'Întreabă-l pe Ahmed despre lucrarea exterioară pe care o ai în vedere.',s3:'Reîmprospătare proprietate',s3d:'Se pot discuta camere, case, chirii și lucrări mai mici.',galleryTitle:'Galerie',galleryCopy:'Aici pot fi adăugate fotografii reale înainte și după din lucrările lui Ahmed.',faqTitle:'Întrebări frecvente',fq1:'Cât de departe ești dispus să te deplasezi?',fa1:'Spune-i lui Ahmed locația lucrării și îți va spune dacă se află în zona lui obișnuită de lucru.',fq2:'Cum obțin o ofertă?',fa2:'Sună-l sau scrie-i lui Ahmed pe WhatsApp cu o scurtă descriere. Fotografiile și locația sunt utile.',fq3:'Pot trimite fotografii mai întâi?',fa3:'Da. Fotografiile sunt o modalitate simplă de a arăta camera sau suprafața înainte de discuție.',fq4:'Cine cumpără vopseaua?',fa4:'Întreabă-l pe Ahmed când vorbiți. Vopseaua și materialele pot fi stabilite pentru fiecare lucrare.',fq5:'Cât va dura lucrarea?',fa5:'Depinde de dimensiune și de pregătirea necesară. Ahmed poate spune mai exact după ce știe detaliile.',fq6:'Ce să trimit când iau legătura?',fa6:'Locația, câteva fotografii și o descriere scurtă sunt cel mai bun început.',contactTitle:'Sună-l pe Ahmed',contactCopy:'Cel mai rapid este să îl suni sau să îi scrii pe WhatsApp și să îi spui de ce ai nevoie.',phoneLabel:'Telefon / WhatsApp',phonePlaceholder:'Numărul lui Ahmed va fi adăugat',hide:'Ascunde',show:'Arată'},
  uk:{navServices:'Послуги',navGallery:'Галерея',navFaq:'Питання',navContact:'Контакти',dropPainting:'Фарбування та оздоблення',dropJobs:'Кімнати, будинки та об’єкти',dropBeforeAfter:'До і після',dropProjects:'Фото робіт',dropTravel:'Район виїзду',dropQuote:'Оцінка роботи',dropPaint:'Фарба та матеріали',kicker:'ФАРБУВАННЯ ТА ОЗДОБЛЕННЯ',intro:'Просте й акуратне фарбування. Розкажіть Ахмеду, що потрібно, і він скаже, чи підходить йому ця робота.',callAhmed:'Дзвінок / WhatsApp Ахмеду',seeGallery:'Переглянути галерею',servicesTitle:'Фарбування та оздоблення',servicesCopy:'Потрібно пофарбувати кімнату, будинок, орендоване житло чи інший простір? Зателефонуйте Ахмеду й коротко опишіть роботу.',s1:'Інтер’єр',s1d:'Стіни, стелі та загальні оздоблювальні роботи.',s2:'Зовнішні роботи',s2d:'Запитайте Ахмеда про зовнішню роботу, яку ви плануєте.',s3:'Оновлення об’єкта',s3d:'Можна обговорити кімнати, будинки, орендовані об’єкти та менші роботи.',galleryTitle:'Галерея',galleryCopy:'Тут можна розмістити справжні фото робіт Ахмеда до і після.',faqTitle:'Поширені питання',fq1:'Як далеко ви готові виїжджати?',fa1:'Скажіть Ахмеду місце роботи, і він повідомить, чи входить воно до його звичайного району.',fq2:'Як отримати оцінку?',fa2:'Зателефонуйте або напишіть Ахмеду у WhatsApp з коротким описом роботи. Фото та місце також допоможуть.',fq3:'Чи можна спочатку надіслати фото?',fa3:'Так. Фото — простий спосіб показати кімнату або поверхню до обговорення роботи.',fq4:'Хто купує фарбу?',fa4:'Запитайте Ахмеда під час розмови. Фарбу й матеріали можна узгодити для кожної роботи.',fq5:'Скільки триватиме робота?',fa5:'Це залежить від обсягу та підготовки. Ахмед зможе сказати точніше, коли знатиме деталі.',fq6:'Що надіслати при першому контакті?',fa6:'Місце, кілька фото та короткий опис — найпростіший початок.',contactTitle:'Зателефонуйте Ахмеду',contactCopy:'Найшвидший спосіб — зателефонувати або написати Ахмеду у WhatsApp і сказати, що вам потрібно.',phoneLabel:'Телефон / WhatsApp',phonePlaceholder:'Номер Ахмеда буде додано',hide:'Сховати',show:'Показати'}
};

const select=document.getElementById('language');

function setLanguage(lang){
  const d=translations[lang]||translations.en;
  document.documentElement.lang=lang;
  document.documentElement.dir=lang==='ar'?'rtl':'ltr';
  document.querySelectorAll('[data-i18n]').forEach(el=>{
    const value=d[el.dataset.i18n];
    if(value) el.textContent=value;
  });
  localStorage.setItem('ah-painting-language',lang);
}

select.addEventListener('change',e=>setLanguage(e.target.value));
const saved=localStorage.getItem('ah-painting-language');
if(saved&&translations[saved]) select.value=saved;
setLanguage(saved&&translations[saved]?saved:'en');

document.querySelectorAll('.navtoggle').forEach(button=>{
  button.addEventListener('click',()=>{
    const item=button.closest('.navitem');
    const open=item.classList.toggle('is-open');
    button.setAttribute('aria-expanded',String(open));
    document.querySelectorAll('.navitem.is-open').forEach(other=>{
      if(other!==item){other.classList.remove('is-open');const b=other.querySelector('.navtoggle');if(b)b.setAttribute('aria-expanded','false');}
    });
  });
});

document.addEventListener('click',e=>{
  if(!e.target.closest('.navitem')){
    document.querySelectorAll('.navitem.is-open').forEach(item=>{item.classList.remove('is-open');const b=item.querySelector('.navtoggle');if(b)b.setAttribute('aria-expanded','false');});
  }
});

document.querySelectorAll('.section-toggle').forEach(button=>{
  button.addEventListener('click',()=>{
    const section=button.closest('.page-section');
    const content=section.querySelector('.section-content');
    const hidden=content.hidden=!content.hidden;
    button.setAttribute('aria-expanded',String(!hidden));
    const lang=document.documentElement.lang;
    button.textContent=(translations[lang]||translations.en)[hidden?'show':'hide'];
  });
});
